#!/usr/bin/env node
/**
 * build-css.js — Bundles css/main.css's @import chain into ONE file.
 *
 * WHY: CSS @import is a SERIAL, render-blocking waterfall — the browser
 * must fetch and parse main.css before it even discovers the 22 files it
 * imports, and those then queue behind it. On GitHub Pages that is a
 * visible white flash / slow first paint on every page load.
 * Bundling keeps the identical cascade order but costs ONE request.
 *
 * The modular files under css/ remain the source of truth — edit those,
 * then run:  node tools/build-css.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ENTRY = path.join(ROOT, 'css', 'main.css');
const OUT = path.join(ROOT, 'css', 'bundle.css');

function inline(file, seen) {
  const dir = path.dirname(file);
  const src = fs.readFileSync(file, 'utf8');
  return src.replace(/@import\s+url\(\s*['"]?([^'")]+)['"]?\s*\)\s*;/g, (m, rel) => {
    const target = path.resolve(dir, rel);
    if (seen.has(target)) return `/* (already bundled: ${rel}) */`;
    seen.add(target);
    if (!fs.existsSync(target)) {
      console.warn('  ! missing import:', rel);
      return m;
    }
    const label = path.relative(path.join(ROOT, 'css'), target);
    return `\n/* ═══════ ${label} ═══════ */\n` + inline(target, seen);
  });
}

const bundled = inline(ENTRY, new Set());
const header = `/* AUTO-GENERATED by tools/build-css.js — DO NOT EDIT.
   Edit the modular files under css/ and re-run:  node tools/build-css.js
   Generated: ${new Date().toISOString()} */\n`;
fs.writeFileSync(OUT, header + bundled);

const before = fs.readdirSync(path.join(ROOT, 'css'), { recursive: true })
  .filter(f => String(f).endsWith('.css')).length;
console.log('✅ css/bundle.css written');
console.log('   ' + (header + bundled).length + ' bytes, replaces ' + before + ' file requests with 1');
