#!/usr/bin/env node
/**
 * build-js.js — Bundles the app's 48 scripts into ONE file.
 *
 * WHY: index.html used to name all 48 individually. Under
 * `max-age=300, must-revalidate` that meant a repeat visit paid 48
 * conditional requests before a single line of the app could run —
 * the slowest part of loading the portal by a wide margin.
 *
 * Bundling keeps the identical execution order but costs ONE request,
 * and because the tag carries a content hash (?v=), the bundle can be
 * cached permanently: a new build changes the URL, so a stale copy is
 * impossible rather than merely unlikely.
 *
 * ORDER IS LOAD-BEARING. project-core.js must precede the other
 * project/* files (they augment ProjectPage via Object.assign), and
 * init.js must stay last. tools/js-manifest.json holds that order and
 * is the single source of truth — edit it when adding a file.
 *
 * The modular files under js/ remain the source of truth for CODE —
 * edit those, then run:  node tools/build-js.js
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const MANIFEST = path.join(__dirname, 'js-manifest.json');
const OUT_REL = 'js/bundle.js';
const OUT = path.join(ROOT, OUT_REL);
const HTML = path.join(ROOT, 'index.html');

const files = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));

// Guard: a file added under js/ but never registered would silently not
// ship. Catch that here rather than as a missing-function error in the
// browser.
const onDisk = [];
(function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full);
    else if (entry.name.endsWith('.js')) {
      onDisk.push(path.relative(ROOT, full).split(path.sep).join('/'));
    }
  }
})(path.join(ROOT, 'js'));

const registered = new Set(files);
const unregistered = onDisk.filter((f) => f !== OUT_REL && !registered.has(f));
if (unregistered.length) {
  console.error('✗ These files exist under js/ but are not in tools/js-manifest.json:');
  unregistered.forEach((f) => console.error('    ' + f));
  console.error('  Add them (in the right load position) and re-run.');
  process.exit(1);
}

const missing = files.filter((f) => !fs.existsSync(path.join(ROOT, f)));
if (missing.length) {
  console.error('✗ Listed in the manifest but missing on disk:');
  missing.forEach((f) => console.error('    ' + f));
  process.exit(1);
}

const parts = files.map((rel) => {
  const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  // A file ending in a //-comment or a statement without a semicolon
  // would otherwise swallow the first line of the next one.
  return `\n/* ═══════ ${rel} ═══════ */\n${src}\n;\n`;
});

const header = `/* AUTO-GENERATED by tools/build-js.js — DO NOT EDIT.
   Edit the modular files under js/ and re-run:  node tools/build-js.js
   Generated: ${new Date().toISOString()} */\n`;

const bundle = header + parts.join('');
fs.writeFileSync(OUT, bundle);

const hash = crypto.createHash('sha256').update(bundle).digest('hex').slice(0, 12);

// Point the shell at the new content. index.html is served no-cache, so
// this hash is what makes a long-lived bundle cache safe.
const html = fs.readFileSync(HTML, 'utf8');
const tagRe = /<script src="js\/bundle\.js(?:\?v=[a-f0-9]*)?"><\/script>/;
if (!tagRe.test(html)) {
  console.error('✗ index.html has no <script src="js/bundle.js"> tag to update.');
  process.exit(1);
}
fs.writeFileSync(HTML, html.replace(tagRe, `<script src="js/bundle.js?v=${hash}"></script>`));

console.log('✅ js/bundle.js written');
console.log(`   ${bundle.length} bytes, replaces ${files.length} file requests with 1`);
console.log(`   index.html -> js/bundle.js?v=${hash}`);
